{% set version = "0.1.2" %}

package:
  name: pymt_sedflux
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/pymt_sedflux/archive/v{{ version }}.tar.gz
  sha256: 48a14582c81003dd8be024ec3dc2350bbc2cc8cffc72127b795f197eaf16ea52

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy =1.11
    - model_metadata
    - sedflux

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - sedflux

test:
  imports:
    - pymt_sedflux

about:
  home: https://github.com/pymt-lab/pymt_sedflux
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: sedflux components wrapped as PyMT plugins.
  dev_url: https://github.com/pymt-lab/pymt_sedflux

extra:
  recipe-maintainers:
    - mcflugen
