{% set version = "0.1.3" %}

package:
  name: pymt_sedflux
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/pymt_sedflux/archive/v{{ version }}.tar.gz
  sha256: 4fccaedb12091443a83e0274ca6d93e82a7ea84a138aef7f1e3d605dbbc29994

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - model_metadata
    - sedflux
    - pathlib  # [py27]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - sedflux
    - pathlib  # [py27]

test:
  imports:
    - pymt_sedflux

about:
  home: https://github.com/pymt-lab/pymt_sedflux
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: sedflux components wrapped as PyMT plugins.
  dev_url: https://github.com/pymt-lab/pymt_sedflux

extra:
  recipe-maintainers:
    - mcflugen
