{% set version = "0.2.0" %}

package:
  name: pymt_sedflux
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/pymt_sedflux/archive/v{{ version }}.tar.gz
  sha256: 38c335b0b84b0dd5dccf9e4516b935eef44f6028d430e9627b7bd7f0e5b7b58f

build:
  number: 4
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [win or py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - numpy
    - sedflux
  run:
    - python
    - setuptools
    - sedflux

test:
  requires:
    - bmi-tester
  commands:
    - bmi-test pymt_sedflux:Avulsion -vvv
    - bmi-test pymt_sedflux:Plume -vvv
    - bmi-test pymt_sedflux:Subside -vvv

about:
  home: https://github.com/pymt-lab/pymt_sedflux
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: sedflux components wrapped as PyMT plugins.
  dev_url: https://github.com/pymt-lab/pymt_sedflux

extra:
  recipe-maintainers:
    - mcflugen
