# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kcr1Km8YBij2g1n/7yenH0C995ylA4ocGboycH4IP6MY4oD70ck/bA2TjjG8ufWfGgsnywqOZVu7oMDS8nMYSkTBsyAycU2PvtCiZxN/vxAhw1UjNunpzb7VD8yDbnk7hyElJieWKaKK8JhfQXwnFbkeSLueCN4eJ5U3UJgFpUrXM1x4vDzw3fwT2qlpT0WNwNMKgAEGFVk1k3m8GjKAZ/XQ3V79Mz+6K87tHAGPbCXztoZQUpgUppKNTLM2kLjIiFdNhQcp9t1UTDrmRsSKoo1sO0bdWnVxubHfq081V/MYgnLNIPsNJ+XOgSJjj1flYnjn2RTKnPZcIhDwK9ebAizkKE4LBqsR7JICaHwzFpMl23+wG5QzYlVpIc3oNgmzuahC+zAwIQpCsVRrFpmf7ufTDAyiC2U3Ss4dY46f/If+IZOq1ztFu6Q/ue6PB1Z4jBTWNUprorckfbjK0r4B7Kd0xLuagKK5Gkp1C8w+DE/Brf/PFmX0xaRHTT09kci/+fnnufiQa7lHYMO6u88ZkEwyBld4hLqPQ3U0tXnGiLvfqz+xEvMSlb8TdllllyTlKYzGqzirkMu65YGPYUYdq5kHCrkKysO064tlaupDZVq3j15XZIfTl2gJQ/Wd7lSmsfgv+XTsy4dcRJR1sPyrDk3ajOKF+UNqa5x+jjvmo50="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
