travis:
  secure:
    BINSTAR_TOKEN: kcr1Km8YBij2g1n/7yenH0C995ylA4ocGboycH4IP6MY4oD70ck/bA2TjjG8ufWfGgsnywqOZVu7oMDS8nMYSkTBsyAycU2PvtCiZxN/vxAhw1UjNunpzb7VD8yDbnk7hyElJieWKaKK8JhfQXwnFbkeSLueCN4eJ5U3UJgFpUrXM1x4vDzw3fwT2qlpT0WNwNMKgAEGFVk1k3m8GjKAZ/XQ3V79Mz+6K87tHAGPbCXztoZQUpgUppKNTLM2kLjIiFdNhQcp9t1UTDrmRsSKoo1sO0bdWnVxubHfq081V/MYgnLNIPsNJ+XOgSJjj1flYnjn2RTKnPZcIhDwK9ebAizkKE4LBqsR7JICaHwzFpMl23+wG5QzYlVpIc3oNgmzuahC+zAwIQpCsVRrFpmf7ufTDAyiC2U3Ss4dY46f/If+IZOq1ztFu6Q/ue6PB1Z4jBTWNUprorckfbjK0r4B7Kd0xLuagKK5Gkp1C8w+DE/Brf/PFmX0xaRHTT09kci/+fnnufiQa7lHYMO6u88ZkEwyBld4hLqPQ3U0tXnGiLvfqz+xEvMSlb8TdllllyTlKYzGqzirkMu65YGPYUYdq5kHCrkKysO064tlaupDZVq3j15XZIfTl2gJQ/Wd7lSmsfgv+XTsy4dcRJR1sPyrDk3ajOKF+UNqa5x+jjvmo50=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
